name = "workers-airtable-form"
type = "javascript"

account_id = "a58a2bb894f4d08f43d3e8e6151dfc1b"
workers_dev = true
# Opt into backwards-incompatible changes through April 5, 2022.
compatibility_date = "2022-05-21"
[vars]
AIRTABLE_BASE_ID = "appXnJ3kGUnoafWp2"
AIRTABLE_TABLE_NAME = "Table"
FORM_URL = "https://workers-airtable-form-8dg.pages.dev"
